# FROM golang:1.16-alpine as build
FROM golang:1.13.8-alpine3.11 as build-env

WORKDIR /app
# COPY go.mod /app
# COPY go.sum /app
# RUN go mod download
COPY *.go /app
# RUN CGO_ENABLED=0 go build -ldflags=”-s -w” -o /docker-simple-app

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o docker-simple-app

FROM scratch

COPY --from=build-env /app/docker-simple-app .
EXPOSE 8888
CMD ["./docker-simple-app"]

